import { Dancing_Script } from 'next/font/google';
import type { Metadata } from "next";
import "./globals.css";
import LayoutWrapper from "@/app/(components)/(layouts)/LayoutWrapper";

const dancingScript = Dancing_Script({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={dancingScript.className}>
      <body className="antialiased">
        <LayoutWrapper>
          { children }
        </LayoutWrapper>
      </body>
    </html>
  );
}
